name: CI - Test Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --junitxml=results.xml --cov=disaster_app --cov-report=html --cov-report=term

    - name: Upload test results (JUnit XML)
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: results.xml

    - name: Upload coverage report (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov
