name: CI - Test Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Restore history.json from last run (if exists)
    - name: Download previous history
      uses: actions/download-artifact@v4
      with:
        name: history
        path: reports
      continue-on-error: true


    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest tests/ --junitxml=results.xml --cov=disaster_app --cov-report=xml --cov-report=term

    - name: Generate final report
      run: |
        python make_report.py results.xml coverage.xml reports/final_report.json

    # Upload updated history.json so next run can use it
    - name: Upload updated history
      uses: actions/upload-artifact@v4
      with:
        name: history
        path: reports/history.json

    - name: Upload test results (JUnit XML)
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: results.xml

    - name: Upload coverage report (XML)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Upload final combined report
      uses: actions/upload-artifact@v4
      with:
        name: final-report
        path: reports/final_report.json
